export * from "./component.interface";
export * from "./definition.interface";
export * from "./injectable.interface";
export * from "./injection.interface";
export * from "./injector.interface";
export * from "./module.interface";
export * from "./provider.interface";
export * from "./record.interface";
export * from "./type.interface";
